sonar.projectKey=pescalerag_mmplayer
sonar.organization=pescalerag

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=mmplayer
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.
sonar.exclusions=**/node_modules/**, **/.expo/**, **/dist/**, **/android/**, **/ios/**, **/web-build/**

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Code coverage reports
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/__tests__/**, **/*.test.ts, **/*.test.tsx, **/node_modules/**, **/.expo/**, **/dist/**, **/android/**, **/ios/**, **/web-build/**, jest.config.js, jest.setup.js

# Explicitly target SonarCloud
sonar.host.url=https://sonarcloud.io